storage:
  value: default
  wizard:
    name: "Storage Configuration"
    kind: cluster_storage

dataset:
  value: object-detection-pets
  workspace: kuberlab-demo
  version: "1.0.0"
  wizard:
    name: "Dataset configuration"
    kind: dataset

code:
  value: object-detection-code
  workspace: kuberlab-demo
  version: "0.0.5"
  wizard:
    name: "Select model with object detection API"
    kind: model

serving_port: 9000

